name: Spring Boot CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Récupérer le code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Installer Java
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'

      # 3. Build
      - name: Build project
        run: mvn clean compile

      # 4. Tests
      - name: Run tests
        run: mvn test

      # 5. Packaging
      - name: Package JAR
        run: mvn package

      # 6. Upload artifact
      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: target/*.jar